// Sample form schema for testing the dynamic form system
export const sampleFormSchema = {
  name: "user-registration",
  description: "User registration form with personal information",
  fields: [
    {
      name: "firstName",
      type: "text",
      label: "First Name",
      required: true,
      minLength: 2,
      maxLength: 50,
      placeholder: "Enter your first name",
    },
    {
      name: "lastName",
      type: "text", 
      label: "Last Name",
      required: true,
      minLength: 2,
      maxLength: 50,
      placeholder: "Enter your last name",
    },
    {
      name: "email",
      type: "email",
      label: "Email Address",
      required: true,
      placeholder: "Enter your email address",
    },
    {
      name: "age",
      type: "number",
      label: "Age",
      required: true,
      min: 13,
      max: 120,
      placeholder: "Enter your age",
    },
    {
      name: "gender",
      type: "dropdown",
      label: "Gender",
      required: true,
      options: ["Male", "Female", "Other", "Prefer not to say"],
    },
    {
      name: "birthDate",
      type: "date",
      label: "Date of Birth",
      required: true,
    },
    {
      name: "phoneNumber",
      type: "text",
      label: "Phone Number",
      required: false,
      placeholder: "Enter your phone number",
      validation: {
        pattern: "^[+]?[1-9]?[0-9]{7,15}$",
        message: "Please enter a valid phone number",
      },
    },
    {
      name: "password",
      type: "password",
      label: "Password",
      required: true,
      minLength: 8,
      placeholder: "Create a password",
    },
    {
      name: "website",
      type: "text",
      label: "Personal Website",
      required: false,
      placeholder: "https://example.com",
    },
    {
      name: "bio",
      type: "text",
      label: "Bio",
      required: false,
      maxLength: 500,
      placeholder: "Tell us about yourself...",
    },
  ],
};
